data InitialProject;
infile "C:\Users\gapa0\Desktop\Initial_Project1_Data-1-1.txt" dlm='09'x DSD missover;
input Patient_ID Age State$ LenghtOfStay TotalCharge Initial_Sugar;
run;
proc print data=InitialProject;
format Initial_Sugar 8.5;
run;
data SecondProject;
infile "C:\Users\gapa0\Desktop\Second_Project1_Data-1-1.txt" dlm='09'x;
input Patient_ID After_Sugar;
run;
proc print data=SecondProject;
format After_Sugar 8.5;
run;
proc sort data=InitialProject;
by Patient_ID;
run;
proc sort data=SecondProject;
by Patient_ID;
run;
data final_1;
merge InitialProject (IN=A)
      SecondProject  (IN=B);
by Patient_ID;
if A=1 or B=1;
run;
data final_;
set final_1;
if cmiss(of _all_) then delete;
run;
proc print data=final_;
run;
proc surveyselect data=final_ method=srs sampsize=1000 out=final_2;
run;
proc print data=final_2;
run;
proc means data=final_2;
var Initial_Sugar After_Sugar;
run;
proc means data=final_2 skewness kurtosis;
run;
proc univariate data=final_2;
var Initial_Sugar After_Sugar;
histogram;
run;
proc ttest data=final_2;
Paired Initial_Sugar * After_Sugar;
run;
